### ISSUE TITLE
Isochrone server is returning 502s

### ISSUE THREAD

**Issue by isovector** [BikeOttawa/maps.bikeottawa.ca-backend#1]
Attempting to change the location on the isochrone map is returning 502s with the response:

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Figured commenting here would be more likely to be noticed than sending an email.

Thanks for the service, it's great!

**Comment by matthewdarwin** [comment]
Seems to need a restart every now and then.
