### ISSUE TITLE
Question: For the OSRM path files, are they maps of Ottawa or just paths that users have drawn?

### ISSUE THREAD

**Issue by lou00011** [BikeOttawa/maps.bikeottawa.ca-backend#2]
We are trying to create a tangentially related project and I would appreciate some insight, thanks!

**Comment by matthewdarwin** [comment]
All data for the maps comes from OSM (Ottawa area data), except for the traffic collision data.  The LTS score is calculated by algorithm before being displayed on the map and sent to the routing algorithm.
